### ISSUE TITLE
Fix suspected Camera/Gallery permissions

### ISSUE THREAD

**Issue by Nuytemans-Dieter** [MichielProost/Perfect-Plate#32]
This is required to use with the image picker: https://pub.dev/packages/permission_handler. List of permissions [here](https://pub.dev/documentation/permission_handler_platform_interface/latest/permission_handler_platform_interface/Permission-class.html#constants).
Also, see [this question](https://stackoverflow.com/questions/61931097/how-to-solve-permissionhandler-error-in-flutter)

**Comment by Nuytemans-Dieter** [comment]
Duplicate in Flutter repo: https://github.com/flutter/flutter/issues/29422

**Comment by MichielProost** [comment]
Should be fixed by tonight. Working on it.

**Comment by MichielProost** [comment]
Help needed from @Nuytemans-Dieter 

This functionality should be tested by another account. For some reason, the "permission screen" does not appear anymore when my account is used.
Try to add a profile picture. Since your "camera permission" is set to False, you should see a "permission screen" asking you to allow camera access.

**Comment by Nuytemans-Dieter** [comment]
> Help needed from @Nuytemans-Dieter
> 
> This functionality should be tested by another account. For some reason, the "permission screen" does not appear anymore when my account is used.
> Try to add a profile picture. Since your "camera permission" is set to False, you should see a "permission screen" asking you to allow camera access.

Everything worked out, right?

**Comment by MichielProost** [comment]
Yes.

For your information. There are a bunch of states the camera permission can be in: undetermined, granted, restricted,...
I've simplified this to 2 states: 1) The user has allowed access. 2) All other states.

This allows me to ask for permission when the camera state is set to False. And to allow permission when the state is set to True.

I'll close the issue, since everything works as it's supposed to.
